# Perceptron Algorithm single layer neural network 
 the following code for found outputs for all Gates , training and testing 
- ### [ AND Gate , NAND Gate , NOR Gate ,OR Gate ]
- ### [AND NOT Gate , NOT AND Gate]
- ### [OR NOT Gate , NOT OR Gate ]

you need install extension [Markdown Preview ](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-preview-github-styles) for edit and preview .md file or Markdown files  
all outputs save in outputs folder as md file as table if you want that or show output in print()
* [Taiz university](https://taiz.edu.ye/en/default.ASPX) - Software Engineering  
    by : [Rafiq7M](https://github.com/Rafiq7M)

In [28]:
import numpy as np
import datetime

In [29]:

# sigmoid activation function 
def sigmoid(z):
    return (1/(1+np.exp(-z)))

In [30]:
def get_training_inputs(gateName='or',b=1):
    if gateName.lower()=='and':
        # training Inputs
        #  # AND Gate
        x=np.array([
            [1 ,1 , b],
            [1 ,-1 , b],
            [-1 ,1 , b],
            [-1 ,-1 , b]])
        t=np.array([1,-1,-1,-1])
    elif gateName.lower()=='nand':
        #  # NAND Gate
        x=np.array([
            [1 ,1 , b],
            [1 ,-1 , b],
            [-1 ,1 , b],
            [-1 ,-1 , b]])
        t=np.array([-1,1,1,1])

    elif gateName.lower()=='or':
        #  # OR Gate
        x=np.array([
            [1 ,1 , b],
            [1 ,-1 , b],
            [-1 ,1 , b],
            [-1 ,-1 , b]])
        t=np.array([1,1,1,-1])
    elif gateName.lower()=='nor':
        #  # NOR Gate
        x=np.array([
            [1 ,1 , b],
            [1 ,-1 , b],
            [-1 ,1 , b],
            [-1 ,-1 ,b]])
        t=np.array([-1,-1,-1,1])
    elif gateName.lower()=='and_not':
        #  # AND NOT Gate
        x=np.array([
            [1 ,1 , b],
            [1 ,-1 , b],
            [-1 ,1 , b],
            [-1 ,-1 ,b]])
        t=np.array([-1,1,-1,-1])
        
    elif gateName.lower()=='not_and':
        #  # NOT AND Gate
        x=np.array([
            [1 ,1 , b],
            [1 ,-1 , b],
            [-1 ,1 , b],
            [-1 ,-1 ,b]])
        t=np.array([-1,-1,1,-1])
        
    elif gateName.lower()=='or_not':
        #  # OR NOT Gate
        x=np.array([
            [1 ,1 , b],
            [1 ,-1 , b],
            [-1 ,1 , b],
            [-1 ,-1 ,b]])
        t=np.array([1,1,-1,1])
    elif gateName.lower()=='not_or':
        #  # NOT OR Gate
        x=np.array([
            [1 ,1 , b],
            [1 ,-1 , b],
            [-1 ,1 , b],
            [-1 ,-1 ,b]])
        t=np.array([1,-1,1,1])
    return x,t

In [31]:
batch=8 #2 iterations
w=np.array([0,0,0]) # initialize weight and bias 
th=0.2
b=0
gateName='AND'
x,t=get_training_inputs(gateName,b)
title=f"{gateName} Gate \n ## with ({batch}) batch , and ({w},{b}) init weights , bias "
print("x= \n",x)
print("t= \n",t)

current_date = datetime.datetime.now().strftime("%Y-%m-%d")
# filename = f"outputs/{title}_outputs_table_{current_date}.md"
filename = f"outputs/{gateName} Gate outputs.md"

x= 
 [[ 1  1  0]
 [ 1 -1  0]
 [-1  1  0]
 [-1 -1  0]]
t= 
 [ 1 -1 -1 -1]


In [32]:

# Write the mdText to a file
def save_outputs_md_file(filepath,mode,mdText,title):
    mdText+="\n---\n"
    initText=f"# {title} \n"
    with open(filepath, mode) as mdFile:
        by="\n\n- By: [Rafiq7M](https://github.com/Rafiq7M)\n"
        mdFile.write(initText+mdText+by)
    print(f"Output table saved in {filepath}")

In [33]:
def perceptron_learning(x,t,batch,w,th):
    mdText = ""
    for i in range(batch):
        batch_x=x
        count=i%4
    # calculate net
        net1=np.sum(batch_x[count]*w.T)
        out=net1

        # when theta =0.2
        if out>=th :
            out =1
        if (out<th )and(out>-th) :
            out =0
        if out<=-th :
            out =-1

        if out == t[count]:
            xdelta=[0,0,0]
            out_str="✅" #"🟢"
        else :
            xdelta=t[count]*batch_x[count]
            out_str="❌"  #"🔴"
        w=np.add(w,xdelta)
        
        # print outputs table
        x_str = ', '.join(map(str, x[count]))
        t_str = ', '.join(map(str, [t[count]]))
        xdelta_str = ', '.join(map(str, xdelta))
        w_str = ', '.join(map(str, w))
        if (count==0) : 
            mdText += f"\n### 🌐 Iteration {(i // 4) + 1}\n\n"
            mdText += f"| {'i'} | {'count'} | {'inputs Xi'} | {'net1'} | {'out'} | {'target'} | {'Delta '} | {'WEIGHTS'} |\n"
            mdText += "|---|---|---|---|---|---|---|---|\n"
        
            print(f"iteration={(i/4)+1}")
            print(f'{"i":^2} {"count":^2}  {"INPUT":^15} {"net1":^5}  {"out":^5} {"TARGET":^10} {"Delta":^15} {"WEIGHTS":^15} ')
            print("=="*45)
           
        mdText += f'| {i} | {count} | {x_str} | {net1} | {out} {out_str}| {t_str} | {xdelta_str} | {w_str} |\n'
        
        print(f'{i} {x_str:^20} {net1:^2} {out} {out_str:^12} {t_str:^1} {xdelta_str:^24} {w_str:10}')
        print()
    
    # 
    mdText += f"\n## Final weights = {w_str}\n"
    mdText += "\n"
    
    print(f"\n## Final  weights = {w_str}\n")
    
    return w,mdText


In [34]:
# test function      
def test_NN (x,t,w):
    mdText ="\n"
    def test_NN (z):
        return np.dot(z,w)
    mdText += f"| 'i' |'inputs Wi' |'target' | 'output' |💱|\n"
    mdText += "|---|---|---|---|---|\n"
    
    
    print(f"\n## Testing\n")
    print(f'{"i":^2} {"INPUT":^15} {"TARGET":^10} {"output":^10}')
        
    for x_i in range(len(x)):
        x_str = ', '.join(map(str, x[x_i]))
        t_str = ', '.join(map(str, [t[x_i]]))
        out=2*int(round(sigmoid(test_NN(x[x_i]))))-1
        if out == t[x_i]:
            out_str="✅" #"🟢"
        else :
            out_str="❌"  #"🔴"
                        
        mdText += f'| {x_i} | {x_str} | {t_str} | {out}|{out_str}|\n'
        print(f'{x_i} {x_str:^20} {t_str:^1}  {out} {out_str:^10}')


    return mdText


## Pred

In [35]:

final_weights,output_md_text=perceptron_learning(x,t,batch,w,th)
save_outputs_md_file(filename,'w',output_md_text,title)
print("done ✅")

iteration=1.0
i  count       INPUT      net1    out    TARGET        Delta          WEIGHTS     
0       1, 1, 0        0  0      ❌       1         1, 1, 0          1, 1, 0   

1       1, -1, 0       0  0      ❌       -1         -1, 1, 0         0, 2, 0   

2       -1, 1, 0       2  1      ❌       -1         1, -1, 0         1, 1, 0   

3      -1, -1, 0       -2 -1      ✅       -1         0, 0, 0          1, 1, 0   

iteration=2.0
i  count       INPUT      net1    out    TARGET        Delta          WEIGHTS     
4       1, 1, 0        2  1      ✅       1         0, 0, 0          1, 1, 0   

5       1, -1, 0       0  0      ❌       -1         -1, 1, 0         0, 2, 0   

6       -1, 1, 0       2  1      ❌       -1         1, -1, 0         1, 1, 0   

7      -1, -1, 0       -2 -1      ✅       -1         0, 0, 0          1, 1, 0   


## Final  weights = 1, 1, 0

Output table saved in outputs/AND Gate outputs.md
done ✅


## Testing

In [36]:
output_md_text=test_NN(x,t,final_weights)
save_outputs_md_file(filename,'a',output_md_text,"Testing "+title)
print("done ✅")


## Testing

i       INPUT        TARGET     output  
0       1, 1, 0        1  1     ✅     
1       1, -1, 0       -1  -1     ✅     
2       -1, 1, 0       -1  -1     ✅     
3      -1, -1, 0       -1  -1     ✅     
Output table saved in outputs/AND Gate outputs.md
done ✅
